### ISSUE TITLE
xAPI alternate request content type strictness.

### ISSUE THREAD

**Issue by ryansmith94** [LearningLocker/learninglocker#999]
**Version**
- xapi-activities v1.1.5
- xapi-agents v1.1.6
- xapi-state v1.1.7
- xapi-statements v1.0.10

**Steps to reproduce the bug**
1. Create an alternate request with content type `application/x-www-form-urlencoded; charset=UTF-8`

**Expected behaviour**
The services should be accepting the request because the following content types should probably be allowed according to the [spec](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#user-content-1.3.s3.b9) as discussed in #998:
- `application/x-www-form-urlencoded; charset=UTF-8`
- `application/x-www-form-urlencoded`

**Actual behaviour**
- The xapi-statements service is accepting content types with other charsets.
- The other services are not accepting content types with UTF-8 as the charset.

**Progress**
- [x] Create PR for xapi-activities (LearningLocker/xapi-activities#16)
- [x] Create PR for xapi-agents (LearningLocker/xapi-agents#11)
- [x] Create PR for xapi-state (LearningLocker/xapi-state#13)
- [x] Create PR for xapi-statements (LearningLocker/xapi-statements#52)
- [x] Add conformance tests to xapi-service
- [x] Release fix for xapi-activities
- [x] Release fix for xapi-agents
- [x] Release fix for xapi-state
- [x] Release fix for xapi-statements
- [x] Release updates for xapi-service

**Comment by andrewdisney** [comment]
Any update on this issue? We are trying to upgrade our environment to PHP7 and upgrading Learning Locker to version 2 is the last item holding us back.

**Comment by ryansmith94** [comment]
Hi @andrewdisney, currently this issue is a medium priority for us because whilst we should accept application/json with a charset of UTF-8, the API passes the conformance tests and is still usable just by removing the charset from the content type header. Since no one else has reported an issue with this it's unlikely that it's causing an issue for anyone right now and at the moment we have tasks to complete that have a higher priority.

In terms of upgrading your environment to PHP 7, I firstly want to be clear that Learning Locker 2 is using Node not PHP. Secondly, I want to be clear that a fix to the issue here will not resolve your issue. Your issue is actually with an invalid request and is not a bug in Learning Locker 2 as [James explained](https://github.com/LearningLocker/learninglocker/issues/998#issuecomment-337603632).
